### ISSUE TITLE
[Packaging] Requesting conda-forge package

### ISSUE THREAD

**Issue by stallam-unb** [wilsonjr/humap#5]
Hi,

Just putting it out there that you might want to consider putting up your package on conda-forge. Many other packages like numpy, scikit-learn, umap, are all available on conda-forge, and managing them through `conda` cli makes it easy to be up-to-date and not worry about dependencies like MKL, which pip doesn't handle well.

As a bonus, I see that this package depends on Eigen, which needs to be manually configured on Windows. Conda-forge already has [eigen available](https://anaconda.org/conda-forge/eigen), which might make this much less error-prone for Windows users, which I assume will be a substantial chunk.

Just as an FYI, [here is a link for conda-forge submission process](https://conda-forge.org/docs/maintainer/adding_pkgs.html).

Thanks!

**Comment by wilsonjr** [comment]
Hi!

Thank you for the suggestion. I agree that the Windows installation is a bit messy.

I'll take publish on this weekend. Thanks!

**Comment by erguntiryaki** [comment]
Dear @wilsonjr,

Thanks for the cool package. I am wondering whether it is a feasible option to provide wheel distributions on PyPI.

Best,

**Comment by wilsonjr** [comment]
@erguntiryaki, of course. Check it if you can locate it now.

I think you will be better served with the conda-forge package (I am just resolving pipeline issues at this exact moment).

I'll be back with updates.

**Comment by erguntiryaki** [comment]
@wilsonjr you are very fast! Thanks for the MacOS wheel. 
As you stated, I would prefer conda-forge for my PC. I was asking mainly for the Google Colab.

I know building wheels for different platforms and Python versions is exhausting.
Just as an FYI if you prefer this option:
- Distributing through [Python's stable ABI](https://stackoverflow.com/questions/69051619/identifying-packages-using-pythons-stable-abi) can be beneficial for compatibility with multiple Python versions.
- [cibuildwheel](https://cibuildwheel.readthedocs.io/en/stable/setup/) can be a good tool to relieve the burden of building wheels for different platforms and Python versions.

Thank you so much.

**Comment by wilsonjr** [comment]
Hi @stallam-unb and @erguntiryaki! Now you can install it using conda: https://anaconda.org/conda-forge/humap

I'll be adding support for M1 macos today (hopefully)

**Comment by stallam-unb** [comment]
> Hi @stallam-unb and @erguntiryaki! Now you can install it using conda: https://anaconda.org/conda-forge/humap
> 
> I'll be adding support for M1 macos today (hopefully)

Thanks! Will be taking it for a spin today.
